### ISSUE TITLE
2.2.9 version breaks things badly.

### ISSUE THREAD

**Issue by karcaw** [chr4-cookbooks/iptables-ng#59]
I cant even get a simple kitchen test to complete:  I get errors such as this:

`Chef::Exceptions::ResourceNotFound
           ----------------------------------
           resource file[/etc/iptables.d/filter/INPUT/default] is configured to notify resource ruby_block[create_rules] with action create, but ruby_block[create_rules] cannot be found in the resource collection. file[/etc/iptables.d/filter/INPUT/default] is defined in /tmp/kitchen/cache/cookbooks/iptables-ng/providers/chain.rb:53:in `edit_chain'
`

my guess is the 'use_inline_resources' use in the lwrp

**Comment by chr4** [comment]
Thanks for reporting.
Does this only affect testing, or is this also hurting in real-life?

**Comment by chr4** [comment]
I'm reverting the `use_inline_resource`. `2.2.10` fixes the issue, sorry for the inconvenience.
