### ISSUE TITLE
Ubuntu 16.04?

### ISSUE THREAD

**Issue by alicebob** [chr4-cookbooks/iptables-ng#68]
Hi,

16.04 is not supported according to the README. Is that correct?

Systemd seems happy enough when changing `netfilter-persistent` back to `iptables-persistent` (it's still a file in /etc/init.d/ and not a proper systemd service, though).

Thanks!

**Comment by chr4** [comment]
No, this is not correct. I'm using this cookbook in production on a lot of Ubuntu-16.04 machines. I'm adapting the README, thanks for spotting!
16.04 is actually also tested in the integration tests.

Regarding the `netfilter-persistent` service, could it be, you're talking about 16.10 or 17.04? On my machines, the systemd service is still called `netfilter-persistent` (having  the `iptables-persistent` and `netfilter-persistent` packages installed).

**Comment by alicebob** [comment]
16.04.2 LTS, xenial. There is no netfilter-persistent package available...

**Comment by alicebob** [comment]
I missed 'universe' in my apt list. Grrr.

**Comment by alicebob** [comment]
Works great now, thanks and sorry for bothering :/

**Comment by chr4** [comment]
Would you mind checking back how this is handled in 16.10/ 17.04? I think it makes sense to have this cookbook working without `universe` enabled. 

No need to apologize :)
